version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: menu_management_system
    restart: always
    environment:
      POSTGRES_DB: menu_management_system
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
